apiVersion: apps/v1
kind: Deployment
metadata:
        name: springmonitoring
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: springmonitoring
        template:
          metadata:
            labels:
               app: springmonitoring
          spec:
                  containers:
                          - name: springbootmonitoring
                            image: samiibnbougatef/springboot:$BUILD_NUMBER
                            imagePullPolicy: Always
                            ports:
                                    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
        name: springmonitoring
spec:
        type: NodePort
        selector:
                app: springmonitoring
        ports:
                - port: 8008
                  targetPort: 8080
                  nodePort: 31000
